---
- name: "update and upgrade packages"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes
    autoremove: yes
  register: result
  until: result is succeeded

- name: "install extra packages"
  package:
    name: "{{ extra_packages }}"
    state: present