- name: Configure the raspberry pi server
  hosts: clients
  become: true
  gather_facts: false

  tasks:
    - include: roles/maintenance/tasks/update-apt-cache.yaml

    - name: "Install Common packages"
      apt:
        name: 
          - vim
          - docker-compose
          - unattended-upgrades
          - inotify-tools
        state: latest

    - include: roles/maintenance/tasks/watchtower.yaml
    - include: roles/maintenance/tasks/daily-reboot.yaml

    - include: roles/security/tasks/setup-fail2ban.yaml
    - include: roles/security/tasks/setup-ufw.yaml

    - include: roles/docker/tasks/install-ghost.yaml
    - include: roles/docker/tasks/install-soulseek.yaml
    - include: roles/docker/tasks/install-miniflux.yaml
    #- include: roles/docker/tasks/install-navidrome.yaml

    - include: roles/scripts/tasks/setup-soulseek-watch.yaml

      #- name: "Create Application directories"
      #  become_user: parker
      #  file:
      #    path: "{{ item }}"
      #    state: directory
      #    mode: "0755"
      #  loop:
      #    - "~/ghost"
      #    - "~/portainer"
      #    - "~/soulseek"
      #    - "~/syncthing"
