- name: Configure the raspberry pi server
  hosts: clients
  become: true
  gather_facts: false

  tasks:
    - name: "Update Apt Cache"
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: result
      until: result is succeeded

    - name: "Install Common packages"
      apt:
        name: 
          - vim
          - docker-compose
          - unattended-upgrades
        state: latest

    - include: roles/security/tasks/setup-fail2ban.yaml
    - include: roles/security/tasks/setup-ufw.yaml

    - include: roles/docker/tasks/install-ghost.yaml
    - include: roles/docker/tasks/install-soulseek.yaml
    - include: roles/docker/tasks/install-miniflux.yaml

      #- name: "Create Application directories"
      #  become_user: parker
      #  file:
      #    path: "{{ item }}"
      #    state: directory
      #    mode: "0755"
      #  loop:
      #    - "~/ghost"
      #    - "~/portainer"
      #    - "~/soulseek"
      #    - "~/syncthing"
