version: "3"

services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000
    ports:
      - "4533:4533"
    volumes:
      - ./data:/data
      - ~/media/music:/music:ro
    restart: unless-stopped
