---
- name: "ensure ufw installed"
  apt: name=ufw state=present

- name: "deny incoming connections"
  ufw:
    rule: deny
    direction: in
  notify:
  - restart ufw

- name: "allow outgoing connections"
  ufw:
    rule: allow
    direction: out
  notify:
  - restart ufw

- name: "allow ssh connections"
  ufw:
    rule: allow
    port: ssh
  notify:
  - restart ufw

- name: "allow soulseek port"
  ufw:
    rule: allow
    port: 50300
  notify:
  - restart ufw

- name: "allow navidrome port"
  ufw:
    rule: allow
    port: 4533
  notify:
    - restart ufw

- name: "allow pairdrop port"
  ufw:
    rule: allow
    port: 3000
  notify:
    - restart ufw

- name: "enable ufw service"
  ufw:
    state: enabled
