---
- name: Install UFW
  apt:
    name:
      - ufw
    state: latest

- name: Deny incoming connections
  ufw:
    rule: deny
    direction: in

- name: Allow outgoing connections
  ufw:
    rule: allow
    direction: out

- name: Allow SSH connections
  ufw:
    rule: allow
    port: ssh

- name: Allow incoming from Soulseek
  ufw:
    rule: allow
    port: "50300"

- name: Enable UFW
  ufw:
    state: enabled
