---
- name: "install fail2ban"
  apt: name=fail2ban state=present

- name: "copy fail2ban configuration"
  template: src=templates/fail2ban.conf.j2 dest=/etc/fail2ban/jail.local
  notify:
    - restart fail2ban