version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    env_file:
      - .env
    environment:
      - TZ=America/Denver
      - WEBPASSWORD=${WEB_PASS}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "84:80/tcp"
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: always
