---
- name: "configure wg-easy"
  become_user: "{{ username }}"
  copy:
    src: ../apps/wg-easy/
    dest: "{{ docker_dir }}/wg-easy/"

- name: "run wg-easy"
  become_user: "{{ username }}"
  docker_compose:
    project_src: "{{ docker_dir }}/wg-easy/"
    state: present
